######################################################################
#
# Project 2: Extending the Bag ADT
#
# Author: A. G. Werschulz
# Date:   12 Feb 2014
#
######################################################################

CXXFLAGS=-Wall

proj2: proj2.cpp VectorBag.cpp VectorBag.h
	$(CXX) $(CXXFLAGS) -o proj2 proj2.cpp

clean:
	@/bin/rm -f *~ \#*\# core* proj2


